### ISSUE TITLE
Error while running script on Ghidra 9.2

### ISSUE THREAD

**Issue by r0ny123** [intezer/analyze-community-ghidra-plugin#11]
I'm getting the following error:

```
>>> Start analyzing file...
Traceback (most recent call last):
  File "C:\Users\Rony\Desktop\analyze-community-ghidra-plugin-master\intezer_analyze_gh_community.py", line 285, in run
    helper.create_function_map(sha256)
  File "C:\Users\Rony\Desktop\analyze-community-ghidra-plugin-master\intezer_analyze_gh_community.py", line 243, in create_function_map
    function_map = self._get_function_map(sha256)
  File "C:\Users\Rony\Desktop\analyze-community-ghidra-plugin-master\intezer_analyze_gh_community.py", line 167, in _get_function_map
    result_url = self._proxy.create_plugin_report(sha256, functions_data)
  File "C:\Users\Rony\Desktop\analyze-community-ghidra-plugin-master\intezer_analyze_gh_community.py", line 106, in create_plugin_report
    if response.status_code == 404:
AttributeError: 'NoneType' object has no attribute 'status_code'
intezer_analyze_gh_community.py> Finished!
```

**Comment by davidt99** [comment]
Can you share the sha256/md5 you sent?

**Comment by r0ny123** [comment]
Sure, here `5c278c04bb19196dc8559d45b9728b3ba0c1bc5cdd20a766f56248e561c6f5a6`.

**Comment by NicoleFishbein** [comment]
Looks like a timeout occurred, please try to rerun it

**Comment by r0ny123** [comment]
Reran it, the error still occurred.

**Comment by r0ny123** [comment]
Reran it, this time something weird occurred here is error:
```
>>>Done building xml. Writing xml...
Traceback (most recent call last):
  File "C:\Users\Rony\ghidra_scripts\intezer_analyze_gh_community.py", line 285, in run
    helper.create_function_map(sha256)
  File "C:\Users\Rony\ghidra_scripts\intezer_analyze_gh_community.py", line 245, in create_function_map
    self.write_xml_file(function_map)
  File "C:\Users\Rony\ghidra_scripts\intezer_analyze_gh_community.py", line 238, in write_xml_file
    output_file = open(PATH_TO_XML, 'w')
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\system32\\items.xml'
intezer_analyze_gh_community.py> Finished!
```

**Comment by NicoleFishbein** [comment]
Try to set a path in PATH_TO_XML (instead of the default one) use a path that your user has access to

**Comment by r0ny123** [comment]
Thanks, I did that but again a timeout occurred as you said but I ran the Intezer IDA plugin, it went perfectly well. I'm going nuts now. Don't why its keep happening.

**Comment by NicoleFishbein** [comment]
Try to analyze the file in [Analyze ](https://analyze.intezer.com/ )and then run the Ghidra plugin

**Comment by r0ny123** [comment]
So, the issue seemed to be resolved now. Didn't know what was happening. Anyway, thanks for the support!
