### ISSUE TITLE
Incompatibility with the current Jython?

### ISSUE THREAD

**Issue by xme** [intezer/analyze-community-ghidra-plugin#5]
I'm testing your script and reached the following problem:

```
>>> Start analyzing file...
Traceback (most recent call last):
  File "/opt/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 272, in run
    helper.create_function_map(sha256)
  File "/opt/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 230, in create_function_map
    function_map = self._get_function_map(sha256)
  File "/opt/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 155, in _get_function_map
    ghidra_plugin_report = self._proxy.get_plugin_report(result_url)
  File "/opt/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 110, in get_plugin_report
    response = self._get(API_URL + result_url)
  File "/opt/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 89, in _get
    return self.session.get(url_path, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 533, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 430, in send
    resp = conn.urlopen(
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 430, in send
    resp = conn.urlopen(
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 589, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 589, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 242, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 27, in is_connection_dropped
    return bool(wait_for_read(sock, timeout=0.0))
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 27, in is_connection_dropped
    return bool(wait_for_read(sock, timeout=0.0))
  File "/usr/lib/python2.7/dist-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/wait.py", line 24, in _wait_for_io_events
    selector.register(sock, events)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/selectors.py", line 344, in register
    key = super(PollSelector, self).register(fileobj, events, data)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/selectors.py", line 197, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/selectors.py", line 181, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/selectors.py", line 50, in _fileobj_to_fd
    raise ValueError("Invalid file object: {0!r}".format(fileobj))
ValueError: Invalid file object: <ssl.SSLSocket object at 0xc15>
```

I found that this error could be related to the Jython version used by Ghidra. Any idea to solve this issue?

**Comment by NicoleFishbein** [comment]
Can you run `sys.version` in the python command line within Ghidra?
In my case the output is : `'2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43) \n[OpenJDK 64-Bit Server VM (AdoptOpenJDK)]'`

**Comment by xme** [comment]
`'2.7.17 (default, Apr 15 2020, 17:20:14) \n[GCC 7.5.0]'`
(System running my Ghidra instance is a Ubuntu 18.04-LTS)

**Comment by TecnoLinux** [comment]
@xme Did you add the correct python path in Linux?

**Comment by xme** [comment]
Yes, I submitted a pull request to adapt it between Win <> Linux.

**Comment by davidt99** [comment]
@xme What version of requests do you have installed?
It looks like it's a known issue in requests: https://github.com/psf/requests/issues/3992

**Comment by xme** [comment]
2.18.4 (the Ubuntu package)
I'll investigate this and let you know!

**Comment by xme** [comment]
I downgraded the Python requests module to 2.7.0. Works perfectly now. I had to add an extra directory for the local modules. I submitted a pull request for this.
