### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by dmoore44** [intezer/analyze-community-ghidra-plugin#9]
I was attempting to analyze a file in Ghidra, but the following set of errors were returned instead, and I'm not real sure where to begin troubleshooting.

`intezer_analyze_gh_community.py> Running...
>>> Program Info:
>>>	winta.exe:
	x86:LE:64:default_windows
	(Wed Sep 02 14:52:52 CDT 2020)
	/Users/dmoore/Documents/repository/samples/gotroj/winta.exe
>>> file SHA : 57150938be45c4d9c742ab24c693acc14cc071d23b088a1facc2a7512af89414
>>> Start analyzing file...
Traceback (most recent call last):
  File "/Users/dmoore/ghidra_scripts/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 284, in run
    helper.create_function_map(sha256)
  File "/Users/dmoore/ghidra_scripts/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 242, in create_function_map
    function_map = self._get_function_map(sha256)
  File "/Users/dmoore/ghidra_scripts/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 166, in _get_function_map
    result_url = self._proxy.create_plugin_report(sha256, functions_data)
  File "/Users/dmoore/ghidra_scripts/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 104, in create_plugin_report
    response = self._post(URLS['create_ghidra_plugin_report'].format(sha256), json={'functions_data': functions_data})
  File "/Users/dmoore/ghidra_scripts/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 91, in _post
    response = self.session.post(url_path, **kwargs)
  File "/Users/dmoore/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/dmoore/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/dmoore/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/dmoore/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
intezer_analyze_gh_community.py> Finished!`

**Comment by davidt99** [comment]
Is it consistent? The error suggests network error.

**Comment by themyops** [comment]
I have a number of emotet samples, and for some the script works, for others I consistently get the error above. All have been uploaded to intezer and the difference is reproducible.

**Comment by dmoore44** [comment]
@davidt99 I've encountered that error on a few samples I've attempted to analyze, so in that regard, yes, it is constant.

**Comment by davidt99** [comment]
@dmoore44 have you analyzed the file in the platform before executing the plugin?

**Comment by davidt99** [comment]
if you can share the sha256, I will be able to take a look for any errors on the backend side.

**Comment by davidt99** [comment]
@dmoore44 if you wish, you can contact our support with the hashes so we can pin point the problems.
